name: Deploy from upstream to fork and GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false # 원본 저장소 토큰 쓰지 않도록

      - name: Set git remote to fork repo
        run: git remote set-url origin https://github.com/asksa1256/rolling.git

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          npm run build
          cp dist/index.html dist/404.html

      - name: Deploy to fork repo GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }} # 원본 저장소에 등록된 GH_PAT (포크 repo 권한)
          repository: asksa1256/rolling
          publish_branch: gh-pages
          publish_dir: ./dist
