# .github/workflows/merge-develop-to-main.yml
name: Auto Merge develop -> main

on:
  push:
    branches:
      - develop

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ✅ push 권한 명시 필요

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0  # 전체 기록 가져오기
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge develop into main
        run: |
          git checkout main
          git pull origin main
          git merge develop --no-edit
          git push origin main