name: Sync & Deploy from Upstream

on:
  schedule:
    - cron: "0 * * * *" # 매시간
  workflow_dispatch: # 수동 트리거도 허용

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout forked repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/Team-07-Project/Team-07-Project.git
          git fetch upstream

      - name: Merge upstream/develop into local develop
        run: |
          git checkout develop
          git merge upstream/develop --no-edit || true
          git push origin develop

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
